security:
    encoders:
        App\Entity\User:
            algorithm: auto


    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    providers:
        jwt_user_provider:
            id: App\Security\JwtUserProvider
        users_in_memory: { memory: null }
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: lazy
#            provider: users_in_memory
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\JwtUserAuthenticator
            provider: jwt_user_provider





